### ISSUE TITLE
Max pooling in character embedding.

### ISSUE THREAD

**Issue by HezhiWang** [YichenGong/Densely-Interactive-Inference-Network#2]
At line 32 in the my.tensorflow.nn.py, you used reduce_max. But in your paper, you said using max pooling after CNN to extract character features. Could you please explain it? Thanks!

**Comment by YichenGong** [comment]
Hi. It's basically a global max pooling over the character sequence length. I used a reduce_max to replace tf.squeeze(tf.max_pooling(tensor, [stride is the sequence length])).
