### ISSUE TITLE
Error on PYTHONHASHSEED=0 python3 train_mnli.py DIIN demo_testing_SNLI --training_completely_on_snli

### ISSUE THREAD

**Issue by MartinXPN** [YichenGong/Densely-Interactive-Inference-Network#5]
Everything is OK up to loading `shared.jsonl` but when `data_processing.py` tries to load it the following error is raised:

```
[1] Loading data SNLI
550152it [00:09, 55502.23it/s]
10000it [00:00, 58533.31it/s]
10000it [00:00, 64180.29it/s]
[1] Loading data MNLI
392702it [00:07, 50719.45it/s]
10000it [00:00, 61434.57it/s]
10000it [00:00, 60510.07it/s]
9796it [00:00, 57942.87it/s]
9847it [00:00, 56161.09it/s]
../data/shared.jsonl
Traceback (most recent call last):
  File "train_mnli.py", line 68, in <module>
    shared_content = load_mnli_shared_content()
  File "..../Densely-Interactive-Inference-Network/python/util/data_processing.py", line 173, in load_mnli_shared_content
    assert shared_file_exist
AssertionError
```

It seems like the data downloader downloads `shared.json` instead of `shared.jsonl` while the training script tries to load a `.jsonl` file.

Everything works fine when downloading shared.jsonl without a script. 
Also you could rename `shared.json` (which redirects to downloading the file) to `shared.jsonl`  in `README`

**Comment by YichenGong** [comment]
Thank you for pointing out. It is updated now.
